### ISSUE TITLE
Migration to Core

### ISSUE THREAD

**Issue by elyasnew** [stimulsoft/Samples-NET.Core-CSharp#2] opened 2017-03-18 14:52 UTC
For getting Pdf report in Asp.net MVC I am working with Stimulsoft 2015. The problem is that I have no idea how to convert my code in order to work with Stimulsoft Core in Asp.net Core. it seems some features are not available anymore in Stimulsoft Core (like StiReport). 

This is the code which works fine in Asp.net MVC

```
    public ActionResult GetReportSnapshot(string sort)
    {

        StiReport report = new StiReport();
        report.Load(Server.MapPath("~/Reports/Jobs.mrt"));

        report["@PrjectId"] = 1;
        report["@OrderBy"] = sort;
        report.Dictionary.Variables["title"] = new Stimulsoft.Report.Dictionary.StiVariable("title", sort);

        report.Render();
        MemoryStream stream = new MemoryStream();
report.ExportDocument(StiExportFormat.Pdf, stream);
        stream.Position = 0;
        FileStreamResult fsr = new FileStreamResult(stream, "application/pdf");
        return fsr;
    }
```
I will appreciate any help.

**Comment by AntonLozovskiy** [comment] 2017-03-20 07:48
Hello,

We try to implement this feature during 1 week.

Thank you.

**Comment by elyasnew** [comment] 2017-03-20 14:26
Ok, perfect

**Comment by VladimirBLR** [comment] 2017-03-27 15:37
Hello,

Please see the "Show-Report-with-Parameters" sample for new version 2017.1.0.4
https://github.com/stimulsoft/Samples-NET.Core-CSharp/tree/master/Show-Report-with-Parameters

Thank you.

**Comment by elyasnew** [comment] 2017-03-27 17:18
Thank you for reply, could you please tell me how can we show the pdf output directly? which means without showing the stimulsoft viewer!

**Comment by elyasnew** [comment] 2017-03-27 17:21
with previous version I did it like this:
`StiReport report = new StiReport();
 report.Load(Server.MapPath("~/Reports/Jobs.mrt"));
 report.Render();
 MemoryStream stream = new MemoryStream();
 report.ExportDocument(StiExportFormat.Pdf, stream);
 stream.Position = 0;
 FileStreamResult fsr = new FileStreamResult(stream, "application/pdf");
 return fsr;`

but since there is no StiReport anymore I have no clue how to do that!

**Comment by VladimirBLR** [comment] 2017-03-27 17:26
Hello,

Please see this sample project:
https://github.com/stimulsoft/Samples-NET.Core-CSharp/tree/master/Export-Report-from-Code

In this example the report is exported to PDF on the server-side without viewer, using the Node.js framework. This is necessary, because this version uses the JS report engine.

Thank you.

**Comment by elyasnew** [comment] 2017-03-27 18:30
I tried that, but it only shows me an empty pdf output, without loading data!

**Comment by VladimirBLR** [comment] 2017-03-28 05:40
Hello,

Please try to install the Node.js framework and run this sample project again.
https://nodejs.org/

Thank you.

**Comment by kubekin2** [comment] 2017-05-17 13:03
If the issue is solved, I close it. Thank you.

**Closed by kubekin2** 2017-05-17 13:03 UTC
